Tamas-Leung/CodeChamp

package-lock.json, src/frontend/package-lock.json, src/frontend/src/app/app-routing.module.ts, src/frontend/src/app/app.module.ts, src/frontend/src/app/startpage/startpage.component.html, src/frontend/src/app/startpage/startpage.component.scss, src/frontend/src/app/startpage/startpage.component.spec.ts, src/frontend/src/app/startpage/startpage.component.ts
Changes:
- Added a home page
- For now start game button leads straight to the problem page
=> Create a start page

src/backend/package-lock.json, src/frontend/package-lock.json, src/frontend/src/app/problem/code-editor/code-editor.component.ts
fileType is not part of CodeModel of the code editor leading to compilation error
=> Fix code editor model error

src/backend/.eslintrc.json, src/backend/package-lock.json, src/backend/package.json, src/backend/src/app.js, src/backend/src/services/ws/index.js
- Allows client to make a connection
- Allows game creation
- Allows joining (sends current list to all connections)
- Allows ending game (sends message to end game to client)
- Allows moving to next round for a lobby
- Allows player's round completion (sends updates to lobby)
Note: orange = sent, black = received
Closes #25 #34
=> Add basic WS functionality

src/backend/package-lock.json, src/backend/package.json, src/backend/src/app.js, src/backend/src/routes/auth.js, src/backend/src/services/ws/index.js, src/frontend/package-lock.json, src/frontend/package.json, src/frontend/src/app/app-routing.module.ts, src/frontend/src/app/app.module.ts, src/frontend/src/app/login/login.component.html, src/frontend/src/app/login/login.component.spec.ts, src/frontend/src/app/login/login.component.ts, src/frontend/src/app/services/auth-guard/auth-guard.service.spec.ts, src/frontend/src/app/services/auth-guard/auth-guard.service.ts, src/frontend/src/app/services/auth/auth.service.spec.ts, src/frontend/src/app/services/auth/auth.service.ts, src/frontend/src/app/startpage/startpage.component.html, src/frontend/src/app/startpage/startpage.component.ts, src/frontend/src/environments/environment.ts, src/frontend/src/index.html
Added simple login page, login redirect and saving of token in local storage. Works with signing into google
Fixes #30
=> Added Google Authentication

src/backend/package-lock.json, src/backend/src/services/ws/index.js, src/frontend/package-lock.json, src/frontend/src/app/app-routing.module.ts, src/frontend/src/app/app.component.ts, src/frontend/src/app/app.module.ts, src/frontend/src/app/lobby/lobby.component.html, src/frontend/src/app/lobby/lobby.component.spec.ts, src/frontend/src/app/lobby/lobby.component.ts, src/frontend/src/app/services/lobby/lobby.service.spec.ts, src/frontend/src/app/services/lobby/lobby.service.ts, src/frontend/src/app/services/websocket/interfaces.ts, src/frontend/src/app/services/websocket/websocket.service.spec.ts, src/frontend/src/app/services/websocket/websocket.service.ts, src/frontend/src/app/startpage/startpage.component.html, src/frontend/src/app/startpage/startpage.component.ts
- Changes menu options to Create Game, Join Game, Logout
- On init of app a websocket connection is created
- Create game button creates a game and redirects to lobby
- New lobby view, shows gameID and players in lobby
- Able to join lobby through /lobby/< gameID>
https://user-images.githubusercontent.com/39676112/210095626-72380073-d426-49e1-a1be-a619f431fa74.mov
- Add textbox to enter game code (to be discussed)
- Format and layout information on lobby
- Add 'Start Game' button in lobby
Closes #41 #42 #43
=> [FE][Lobby] Create game lobby w/ WebSocket connections

src/frontend/src/app/startpage/startpage.component.html
- Adds feature to join lobby by code
- Adds input and redirects to the lobby 
- Button disabled when lobby code is null
https://user-images.githubusercontent.com/39676112/210357024-6e9f4725-d0a5-458c-9e4b-7eef52250eb4.mov
Closes #35 
- Fix styling, ideally using material components/buttons (less hassle when modifying)
=> [FE][Lobby] Add join lobby by code feature

src/backend/package-lock.json, src/backend/package.json, src/backend/src/services/ws/index.js
- Changes gameIDs to readable (WordWord) from UUIDs
Closes: #80
=> [BE][Lobby] Add readable game IDs

src/backend/package-lock.json, src/backend/package.json, src/backend/src/services/ws/index.js
- Uses human-readable-ids to create ids that make sense and are easier to read
| Before  | After |
| - | - |
| ![Screenshot 2023-01-03 at 5 23 38 PM](https://user-images.githubusercontent.com/39676112/210548054-5eeacc27-84c8-4611-86f2-2ff0e0860140.png) | ![Screenshot 2023-01-04 at 6 39 48 AM](https://user-images.githubusercontent.com/39676112/210548089-aa6ce0a2-4580-4705-bc67-60fc9148d9b9.png)|
Updates #81 #80
=> [BE][Lobby] Update gameIDs to better word combinations

src/backend/package-lock.json, src/backend/src/app.js, src/backend/src/routes/judge.js, src/backend/src/services/ws/index.js, src/frontend/src/app/app.module.ts, src/frontend/src/app/problem/code-editor/code-editor.component.ts, src/frontend/src/app/problem/code-editor/submit-dialog.component.html, src/frontend/src/app/problem/end-game-dialog.component.html, src/frontend/src/app/problem/problem.component.html, src/frontend/src/app/problem/problem.component.ts, src/frontend/src/app/problem/solution-submit/solution-submit.service.ts, src/frontend/src/app/services/lobby/lobby.service.ts, src/frontend/src/app/services/websocket/websocket.service.ts, src/frontend/src/app/types/EndData.ts, src/frontend/src/app/types/PlayerData.ts
- Changed websocket logic a bit
- added next round and end round functionality
- added show players completed
- Added win screen
Next round
https://user-images.githubusercontent.com/57273388/211983441-1eaa3639-ab8b-41b5-a3c9-b6748ace0c67.mp4
End game
https://user-images.githubusercontent.com/57273388/211983506-532c7bae-4bd3-4b3b-a4c8-3c26ec44e9e4.mp4
=> Added next round and end round functionaility

src/backend/src/app.js, src/backend/src/services/ws/index.js, src/frontend/src/app/lobby/lobby.component.ts, src/frontend/src/app/services/websocket/interfaces.ts, src/frontend/src/app/services/websocket/websocket.service.ts
https://user-images.githubusercontent.com/57273388/217131249-d52088c2-2aca-415e-8a04-f76ef3372214.mp4
Also disconnects old websockets if new client of same email connects
https://user-images.githubusercontent.com/57273388/217131647-03a9e481-0009-4a37-87f9-8935daaa548a.mp4
=> Added leaving and prevent backing

src/backend/src/app.js, src/backend/src/services/ws/index.js, src/frontend/src/app/problem/problem.component.ts, src/frontend/src/app/services/websocket/interfaces.ts, src/frontend/src/app/services/websocket/websocket.service.ts
Fixes #91 
https://user-images.githubusercontent.com/57273388/217140261-1ee3faa2-bf1f-4c04-a666-05ac0f5316de.mp4
=> Added Reconnections

src/backend/src/app.js, src/backend/src/database/mongoose.js, src/backend/src/database/schemas/matchs.js, src/backend/src/routes/matchs.js, src/backend/src/services/matchs/index.js, src/backend/src/services/ws/index.js
=> Added matches

src/frontend/src/app/problem/problem.component.html, src/frontend/src/app/problem/problem.component.scss
Player status with ring + name + text
Multiple players
https://user-images.githubusercontent.com/39676112/218281380-9e0a6559-3d33-42e3-b9c3-f0d580b806a2.mp4
=> [FE][Problem] Update player status in problem view

src/frontend/src/app/lobby/lobby.component.scss, src/frontend/src/app/lobby/lobby.component.ts
- Adds cursor on hover
- Displays snackbar on click (See bottom of screen)
https://user-images.githubusercontent.com/39676112/218281604-bb448003-9a1f-4923-a070-7b0aa0f1557c.mov
=> [FE][Lobby] Add action indicator and feedback to copy code

src/frontend/src/app/problem/code-editor/code-editor.component.html, src/frontend/src/app/problem/code-editor/code-editor.component.ts, src/frontend/src/app/problem/problem.component.html
Submission done / no submission being judged:
Submission pending:
=> Prevent submissions while current one is pending + show indicators

src/backend/src/services/ws/index.js, src/frontend/src/app/problem/problem.component.html, src/frontend/src/app/problem/problem.component.scss, src/frontend/src/app/problem/problem.component.ts, src/frontend/src/app/services/lobby/lobby.service.ts, src/frontend/src/app/services/websocket/websocket.service.ts
Fixes #105 
https://user-images.githubusercontent.com/57273388/218283750-1bba2e26-b0dc-4790-bca3-65519dd20142.mp4
=> Added Timer

src/frontend/src/app/app-routing.module.ts, src/frontend/src/app/app.module.ts, src/frontend/src/app/end/end.component.html, src/frontend/src/app/end/end.component.scss, src/frontend/src/app/end/end.component.spec.ts, src/frontend/src/app/end/end.component.ts, src/frontend/src/app/problem/end-game-dialog.component.html, src/frontend/src/app/problem/problem.component.ts, src/frontend/src/app/services/lobby/lobby.service.ts, src/frontend/src/app/startpage/startpage.component.ts
Fixes #108 
https://user-images.githubusercontent.com/57273388/218246619-602a3e08-8d00-4875-ac66-7d2ed2e0aa9f.mp4
=> Added win/lose screen

src/frontend/src/app/lobby/lobby.component.html, src/frontend/src/app/lobby/lobby.component.scss, src/frontend/src/app/problem/problem.component.html
=> Disabled start button and removed old player list

src/backend/src/routes/judge.js, src/backend/src/services/judge/docker.js, src/backend/src/services/judge/index.js, src/backend/src/services/judge/judge-verdict.js
Closes #88
Wrong Answer:
Time Limit Exceeded:
Memory Limit Exceeded:
Code Error:
Correct Answer:
(Fingers too slow to catch it before the redirect)
=> Detect and return appropriate judge codes

src/frontend/src/app/problem/problem-description/problem-description.component.html, src/frontend/src/app/problem/problem-description/problem-description.component.scss, src/frontend/src/app/services/problems/problems.service.ts
=> [FE] Problems desc testcases

src/frontend/src/app/problem/problem.component.html, src/frontend/src/app/problem/problem.component.scss, src/frontend/src/app/problem/problem.component.ts
- Adds border and changes colour when warning reached
- Displays snackbar when warning reached (Updated dialog text: 5 minutes remaining!)
- Adds player status view and displays num spots left in next round
https://user-images.githubusercontent.com/39676112/218308788-993eb55a-4943-440c-8b8a-f0505d175724.mov
Player status
=> [FE][Problem] Update status bar of problem view

src/frontend/package-lock.json, src/frontend/package.json, src/frontend/src/app/app.module.ts, src/frontend/src/app/problem/code-editor/code-editor.component.html, src/frontend/src/app/problem/code-editor/code-editor.component.scss, src/frontend/src/app/problem/code-editor/code-editor.component.ts, src/frontend/src/app/problem/problem.component.html, src/frontend/src/app/problem/problem.component.ts, src/frontend/src/app/problem/solution-submit/solution-submit.service.ts, src/frontend/src/app/problem/submission-list/submission-list.component.html, src/frontend/src/app/problem/submission-list/submission-list.component.scss, src/frontend/src/app/problem/submission-list/submission-list.component.spec.ts, src/frontend/src/app/problem/submission-list/submission-list.component.ts, src/frontend/src/app/types/Result.ts, src/frontend/src/app/types/SubmissionResult.ts
Empty View:
One Submission:
The status of the latest submission will be shown next to the submit button.
Multiple submission
Future improvement: Code formatting for previous submissions
=> Add submission view

src/backend/src/routes/matchs.js, src/frontend/src/app/leaderboard/leaderboard.component.html, src/frontend/src/app/leaderboard/leaderboard.component.scss, src/frontend/src/app/leaderboard/leaderboard.component.ts, src/frontend/src/app/services/leaderboard/leaderboard.service.spec.ts, src/frontend/src/app/services/leaderboard/leaderboard.service.ts
- Adds LB service
- Updates LB view with realtime data
- Update styling
=> [FE][Leaderboard] Populate leaderboard with data

src/backend/src/services/ws/index.js
- Fixes reconnect bug by adding leave option when disconnecting client
=> [BE][Bug] Fix reconnect bug

src/backend/src/routes/judge.js, src/backend/src/services/judge/index.js, src/frontend/src/app/problem/code-editor/code-editor.component.ts, src/frontend/src/app/problem/submission-list/submission-list.component.html, src/frontend/src/app/types/SubmissionResult.ts
Will show on code errors to assist the user in debugging:
=> Show stderr to user when appropriate

src/frontend/src/app/myprofile/myprofile.component.html
=> [FE]Fixed grammar issue on profile page

src/backend/src/services/judge/languages.js, src/frontend/src/app/problem/code-editor/code-editor.component.html, src/frontend/src/app/problem/code-editor/code-editor.component.ts, src/frontend/src/app/types/Language.ts
=> Add Python support

src/frontend/src/app/problem/code-editor/code-editor.component.html, src/frontend/src/app/problem/code-editor/code-editor.component.scss, src/frontend/src/app/problem/problem.component.html
=> Improve UI for language selection
